name: haweel
description: Haweel Flutter App (clean runnable demo)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   # هذا السطر مهم لدعم GlobalMaterialLocalizations
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.5.0
  shared_preferences: ^2.5.3
  firebase_core: ^2.32.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
